#!/usr/bin/env python3
"""
Boruta Feature Selection Analysis Tool

Accepts a CSV file with features and a target column, runs Boruta analysis,
and outputs feature_config.json with confirmed, tentative, and rejected features.
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
from boruta import BorutaPy
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor


def load_csv(file_path: str) -> pd.DataFrame:
    """Load CSV file into a DataFrame."""
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"CSV file not found: {file_path}")

    df = pd.read_csv(path)
    print(f"Loaded {len(df)} rows and {len(df.columns)} columns from {file_path}")
    return df


def run_boruta_analysis(
    df: pd.DataFrame,
    target_column: str,
    task_type: str = "classification",
    max_iter: int = 100,
    random_state: int = 42,
    n_estimators: int = 100,
    verbose: int = 1
) -> dict:
    """
    Run Boruta feature selection analysis.

    Args:
        df: DataFrame with features and target
        target_column: Name of the target column
        task_type: 'classification' or 'regression'
        max_iter: Maximum iterations for Boruta
        random_state: Random seed for reproducibility
        n_estimators: Number of trees in the random forest
        verbose: Verbosity level (0=silent, 1=progress, 2=detailed)

    Returns:
        Dictionary with feature categorization results
    """
    if target_column not in df.columns:
        raise ValueError(f"Target column '{target_column}' not found in CSV. Available columns: {list(df.columns)}")

    # Separate features and target
    feature_columns = [col for col in df.columns if col != target_column]
    X = df[feature_columns].values
    y = df[target_column].values

    # Handle missing values
    if np.isnan(X).any():
        print("Warning: Found NaN values in features. Filling with column means.")
        df_features = df[feature_columns].fillna(df[feature_columns].mean())
        X = df_features.values

    if pd.isna(y).any():
        raise ValueError("Target column contains missing values. Please clean your data.")

    print(f"\nRunning Boruta analysis...")
    print(f"  Task type: {task_type}")
    print(f"  Features: {len(feature_columns)}")
    print(f"  Samples: {len(y)}")
    print(f"  Max iterations: {max_iter}")

    # Select appropriate estimator
    if task_type == "classification":
        estimator = RandomForestClassifier(
            n_estimators=n_estimators,
            n_jobs=-1,
            random_state=random_state,
            max_depth=5
        )
    else:
        estimator = RandomForestRegressor(
            n_estimators=n_estimators,
            n_jobs=-1,
            random_state=random_state,
            max_depth=5
        )

    # Run Boruta
    boruta = BorutaPy(
        estimator=estimator,
        n_estimators='auto',
        max_iter=max_iter,
        random_state=random_state,
        verbose=verbose
    )

    boruta.fit(X, y)

    # Categorize features
    confirmed_features = []
    tentative_features = []
    rejected_features = []

    for i, col in enumerate(feature_columns):
        if boruta.support_[i]:
            confirmed_features.append(col)
        elif boruta.support_weak_[i]:
            tentative_features.append(col)
        else:
            rejected_features.append(col)

    # Enabled features = confirmed + tentative
    enabled_features = confirmed_features + tentative_features

    print(f"\nResults:")
    print(f"  Confirmed features: {len(confirmed_features)}")
    print(f"  Tentative features: {len(tentative_features)}")
    print(f"  Rejected features: {len(rejected_features)}")

    return {
        "enabled_features": enabled_features,
        "confirmed_features": confirmed_features,
        "tentative_features": tentative_features,
        "rejected_features": rejected_features,
        "generated_at": datetime.now().isoformat(),
        "notes": "Auto-generated by Boruta analysis. Review tentative features."
    }


def save_feature_config(results: dict, output_path: str = "feature_config.json"):
    """Save results to JSON file."""
    with open(output_path, 'w') as f:
        json.dump(results, f, indent=2)
    print(f"\nFeature config saved to: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Run Boruta feature selection analysis on a CSV file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python boruta_analysis.py data.csv --target target_column
  python boruta_analysis.py data.csv --target label --task regression
  python boruta_analysis.py data.csv --target y --max-iter 200 --output results.json
        """
    )

    parser.add_argument(
        "csv_file",
        help="Path to the input CSV file"
    )
    parser.add_argument(
        "--target", "-t",
        required=True,
        help="Name of the target column in the CSV"
    )
    parser.add_argument(
        "--task",
        choices=["classification", "regression"],
        default="classification",
        help="Type of ML task (default: classification)"
    )
    parser.add_argument(
        "--max-iter",
        type=int,
        default=100,
        help="Maximum iterations for Boruta (default: 100)"
    )
    parser.add_argument(
        "--n-estimators",
        type=int,
        default=100,
        help="Number of trees in random forest (default: 100)"
    )
    parser.add_argument(
        "--output", "-o",
        default="feature_config.json",
        help="Output JSON file path (default: feature_config.json)"
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility (default: 42)"
    )
    parser.add_argument(
        "--quiet", "-q",
        action="store_true",
        help="Suppress Boruta progress output"
    )

    args = parser.parse_args()

    try:
        # Load data
        df = load_csv(args.csv_file)

        # Run analysis
        results = run_boruta_analysis(
            df=df,
            target_column=args.target,
            task_type=args.task,
            max_iter=args.max_iter,
            n_estimators=args.n_estimators,
            random_state=args.seed,
            verbose=0 if args.quiet else 2
        )

        # Save results
        save_feature_config(results, args.output)

        print("\nDone!")
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
